jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 2

  steps:
  - task: NodeTool@0
    inputs:
      version: $(node_version)
    displayName: 'Install Node.js'
   
  - script: |
      npm install
      npm run vscode:prepublish
    displayName: Install Dependencies and Compile Sources
  
  - script: |
      npm run tslint
    displayName: Run TSLint

  - script: |
      npm test --silent
    displayName: Run Unit Tests
    condition: ne(variables['Agent.OS'], 'Linux')